### PR TITLE
Upgrade to support Laravel 5.5 - resolves #11

### LINKED ISSUE #11: Is this project abandoned?
Would be nice to have it updated to support 5.5+.

### PR DESCRIPTION
**Pull request by jorgenb**
- Renamed the fire() methods to handle()
- Upgrading to phpunit/phpunit to 6 allows tests to pass.

### CODE REVIEW

**Comment by jorgenb** [comment]
Not sure how you want to handle multiple php version requirements...

Maybe have users explicitly require v0.2.2 if they are on php 5.6.4.

**Comment by Jorijn** [comment]
Hi @jorgenb 

Thanks for this addition! Would you be able to add a test for the file `SecuritySlackNotification.php` too? I see it's not fully covered, yet.

Thanks.

**Comment by jorgenb** [comment]
@Jorijn I've added tests.

Please note `php artisan security:slack` only works on 5.5.

You might want to update the readme to reflect this. Also, maybe change `LCS_EMAIL_WITHOUT_VULNERABILITIES` to something more generic that can be used for both commands (email and slack).

**Comment by Jorijn** [comment]
I'm merging this into develop. Thanks @jorgenb! I'm going to update it to include Laravel 5.6 as well.

**Pull request merged**
