### PR TITLE
Make Laravel 5.8 compatible

### PR DESCRIPTION
**Pull request by DevDavido**
This PR makes the package Laravel 5.8 compatible :)

### CODE REVIEW

**Comment by DevDavido** [comment]
Tests need fixes

**Comment by Jorijn** [comment]
As looked at here: https://laravel-news.com/laravel-release-process

Laravel 5.5 LTS seems to have expired almost a year ago. However, Laravel 5.6 and 5.7 are still supported. Your PR removes support for those legacy versions and I would like to retain some backwards compatibility for people currently using this package and unable to upgrade to a newer (LTS) version of Laravel. 

Did you remove these supported versions with anything other in mind? If so, please share. I'm always able to remove backwards compatibility by semver tagging the package with a v2.0.0 tag but I don't see any reason to do so right now.

**Comment by DevDavido** [comment]
Yes, my intention was to tag a new major version as [I wrongly assumed that 5.8 would be an LTS release](https://laravel.com/docs/5.8/releases). Turns out it is not. In that case it's better to just modify this PR to make it 5.8 compatible without breaking 5.5 support? :)

**Comment by DevDavido** [comment]
The current PR is backward compatible and supports the new Laravel version. Would you like to tag a new version @Jorijn?

**Comment by Jorijn** [comment]
Thank you @DevDavido! I'll try and review your code this weekend. It it's all good, I'll push out v1.1.0.

**Comment by matijakovacevic** [comment]
Add (in a) commit message "resolves #18" to close the issue

**Pull request merged**
