### PR TITLE
Laravel 9.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 9.x.

**Before merging**, you need to:

- Checkout the `l9-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: Shift detected a dependency for the `laravel/framework`. Unless you have a special requirement for depending on the entire Laravel framework, it's recommended to add dependencies for the specific `illuminate` packages instead.

**Comment by laravel-shift** [comment]
:warning: Shift detected GitHub Actions which run jobs using a version `matrix`. Shift attempted to [update your configuration](https://github.com/Jorijn/laravel-security-checker/pull/40/commits/448f171cc06ac29810d6112460a3c58d627b5d30?w=1) for Laravel 9. However, you should review these changes to ensure the desired combination of versions are built for your package.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/laravel-security-checker.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "jorijn/laravel-security-checker": "dev-l9-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by davidhsianturi** [comment]
@Jorijn can this be merged?

**Comment by Jorijn** [comment]
I'd love to but haven't had the chance to test it. Can you confirm it's working?

**Comment by davidhsianturi** [comment]
installation failed on my end
Screen Shot 2022-02-11 at 11 03 23

seems like the `enlightn/security-checker` needs Symfony 6?

**Comment by jasonmccreary** [comment]
@davidhsianturi, yes, Laravel 9 requires Symfony 6.

**Comment by Jorijn** [comment]
Hi guys. 

I'm working on adding Laravel 9 support and polishing up some stuff. Will be shipping it soon.

@jasonmccreary thanks for providing the starting point!

Jorijn

**Comment by Jorijn** [comment]
@MelchiorKokernoot just published with v2.3.0 :)

I'm closing this PR as it is been replaced. Thanks @jasonmccreary

**Pull request closed without merging**
