### PR TITLE
Laravel 11.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 11.x.

**Before merging**, you need to:

- Checkout the `l11-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: The latest version of Laravel has a dependency for `phpunit/phpunit` of `^10.5`. If you would like to also upgrade your tests, you may run the [PHPUnit 10 Shift](https://laravelshift.com/upgrade-phpunit-10) for free.

**Comment by laravel-shift** [comment]
:warning: Shift detected GitHub Actions which run jobs using a version `matrix`. Shift attempted to [update your configuration](https://github.com/Jorijn/laravel-security-checker/pull/46/commits/25eea5c68693acc6aac9c5e60d620262ec22c4fe?w=1) for Laravel 11. However, you should review these changes to ensure the desired combination of versions are built for your package.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/laravel-security-checker.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "jorijn/laravel-security-checker": "dev-l11-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by DevDavido** [comment]
Hey @Jorijn could you merge this after the PHPUnit 10 shift, please? I'd love to have this in the projects using L11.

**Comment by Jorijn** [comment]
@DevDavido  would you be interested in becoming a maintainer of this package? I am very strained for time unfortunately.

**Comment by DevDavido** [comment]
@Jorijn Thanks for the maintainer role consideration, unfortunately I don't have the bandwidth to take it on at this time. However, I could help out by migrating the package for Laravel 11 compatibility based on this PR here. What do you think?

**Comment by Jorijn** [comment]
@DevDavido that's too bad, but thanks anyway. If you could help out, then please. I noticed some tests were failing, which prevented me from merging this PR blindly and tagging a new version.

**Comment by DevDavido** [comment]
@Jorijn Please see the PR #47 which fixes the test issues and adds additional PHP 8.3 test support.

**Comment by Jorijn** [comment]
Hey @DevDavido, thanks a lot for the work you've done on this change. I've released the change as v2.5.0.

**Pull request closed without merging**
